version: 2.1

anchors:
  context: &context
    context: shared

  default_job_config: &default_job_config
    working_directory: /home/circleci/plugin
    machine:
      image: ubuntu-2004:202201-02

jobs:
  build_package_release:
    <<: *default_job_config
    steps:
      - checkout
      - run:
          name: Getting GV test/build tools
          command: |
            git clone git@github.com:gravityview/Tooling.git /home/circleci/tooling
      - restore_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Installing build dependencies
          command: |
            /home/circleci/tooling/build-tools/build_tools.sh npm -o install
      - save_cache:
          key: node-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Building and packaging
          command: |
            /home/circleci/tooling/build-tools/build_tools.sh grunt -o "less uglify wp_readme_to_markdown"
            if [ "${CIRCLE_BRANCH}" != "main" ]; then
              /home/circleci/tooling/build-tools/build_tools.sh package_build -o "gravity-forms-business-hours gravity-forms-business-hours.php --include-hash"
            else
              /home/circleci/tooling/build-tools/build_tools.sh grunt -o translate
              [[ $(git diff languages/gravity-forms-business-hours.pot | grep +msgid) ]] && /home/circleci/tooling/build-tools/build_tools.sh tx -o "push -s"
              /home/circleci/tooling/build-tools/build_tools.sh tx -o "pull -f -a --parallel --no-interactive"
              /home/circleci/tooling/build-tools/build_tools.sh package_build -o "gravity-forms-business-hours gravity-forms-business-hours.php $([[ $(git log -n 1 | grep "\[skip release\]") ]] && echo --include-hash)"
            fi
            mkdir .release
            cp gravity-forms-business-hours-*.zip .release
      - run:
          name: Creating a GitHub release
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git config user.email "support@gravityview.co"
              git config user.name "GravityView - CI"
              /home/circleci/tooling/build-tools/build_tools.sh create_release -o "gravity-forms-business-hours.php $(ls gravity-forms-business-hours-*.zip)"
            fi
      - run:
          name: Notifying GravityView Release Manager
          command: |
            if ! [[ $(git log -n 1 | grep "\[skip notify\]") ]]; then
              /home/circleci/tooling/build-tools/build_tools.sh announce_build -o "gravity-forms-business-hours.php $(ls gravity-forms-business-hours-*.zip) --with-circle"
            fi
      - store_artifacts:
          path: .release
          destination: release

workflows:
  version: 2
  test_and_package:
    jobs:
      - build_package_release:
          <<: *context

